### ISSUE TITLE
nostrmarket

### ISSUE THREAD

**Issue by motorina0** [lnbits/market#6]
### TODO

- [ ] #7 @talvasconcelos 
- [x] #8@motorina0 
-  `shipping zones` @motorina0 
   - [x] unit cannot be changed 
   -  [x] `stall` has a `sipping_zone` (not the other way around)
- `merchant` @motorina0 
  - [x] has a key-pair
  - ~~can select a subset of all the relays available in `nostrclient`~~
  - [x] every `create` or `update` event is published to the relays
  - [x] SQL table: (user_id, private_key, public_key, config: json)
  - [x] show/hide key pair 
- `customer` UIs: @talvasconcelos 
   - [x] UI for add/remove pubkeys of `merchants`
   - [x] UI for add/remove relays. Plus default hardcoded default relays.
   - [x] migrate `client` <-> `merchant` chat to `nostr`
     - the messages are also persisted in the `messages` table
     - `merchant` uses `nostrclient` to be notified about events
   - `market/stalls`
     - [x] remove all HTTP calls
     - [x] connect via websockets to relays
     -  shopping cart experience takes place here
   - `market/market`
     - [x] remove all HTTP calls
     - [x] connect via websockets to relays
     - [x] customer can create a list of `merchant` public keys
 - [x] `merchant` UI @motorina0 
![image](https://user-images.githubusercontent.com/2951406/221628821-ee3b3f54-0816-4b64-89c0-30dfadc249a8.png)

### Other:
 - [ ] make product description optional
 - [x] ~~should `shipping_zone` be in `orders` table? we have the `product` so we can get the `stall` and the shipping zone if we need~~
 - [ ] `orders.shipped` -> send DM to `customer` on shipped true
 - [x] SQL tables: 
      - [x] `shippingzone`, `invoiceid` -> `shipping_zone`, `invoice_id`
      - [x] use snake case everywhere
      - `product`:
         - [x] `product` column rename to `product.name`
         - [x] `price`, `rating` -> not `int`, but `float`
         - [x] `stall` -> `stall_id`
      - [x] `settings` -> do we need it?
        - no, will store this data in `merchants` table 
      - `stall`:
        - should it have a `currency` column - YES
        - why does it have a `publickey`? where is the `privatekey`? ?
        - [x] `rating` -> make it `float`
      - `zones`:
        - [x] `cost` - should be `float`, not `text`

### Clarify
 - ~~custom relays for stalls. How do they integrate with `nostrclient`?~~
 - where will `market/stalls` and `market/market` get the default relays list since they must make http calls to LNbits?
   - hardcode and add manually

### Notes:
 - a market aggregates multiple `merchants` (via pubkey)

**Comment by arbadacarbaYK** [comment]
Awesome! 

Only messages from and to the merchants pubkey/s which are connected to an order are stored, right ? 
Worried about how to correlate them, spam-amounts of messages, how to delete them, what could be sneaked into the db..

**Comment by motorina0** [comment]
> Only messages from and to the merchants pubkey/s w

Good point, currently all DMs are stored because a customer can ask in writing a merchant for details on a certain product.
A `blocked pubkey list` should solve the spam/scam accounts.

**Comment by arbadacarbaYK** [comment]
I would not block every pubkey that is not related to an order but allow every, that belongs to an order :P Yes i guess that would fix it. All messages from non-customers can be read on nostr..
